apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nqkvzha9e-nodejs
  janus-idp.io/tekton: nqkvzha9e-nodejs
  backstage.io/kubernetes-id: nqkvzha9e-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nqkvzha9e-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
